server:
  port: 8080

spring:
  application:
    name: hr-sphere

  datasource:
    url: jdbc:h2:mem:hr-sphere-db;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE

    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: INFO
    com.hr.sphere: INFO

